apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: smokeylito-admin
spec:
  selector:
    matchLabels:
      app: smokeylito-admin
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: smokeylito-admin
    spec:
      containers:
      - name: smokeylito-admin
        image: fredrikpalmer/smokeylito-admin:1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: smokeylito-admin
spec:
  type: LoadBalancer
  selector:
    app: smokeylito-admin
  ports:
  - port: 3000
    targetPort: 3000

