export const REQUEST_SMOKETEST_TARGETAPPLICATIONS = 'REQUEST_SMOKETEST_TARGETAPPLICATIONS';
export const RECEIVE_SMOKETEST_TARGETAPPLICATIONS = 'RECEIVE_SMOKETEST_TARGETAPPLICATIONS';
export const LOADER_ON = 'LOADER_ON';
export const LOADER_OFF = 'LOADER_OFF';
