export const REQUEST_SMOKETESTS = 'REQUEST_SMOKETESTS';
export type REQUEST_SMOKETESTS = typeof REQUEST_SMOKETESTS;

export const RECEIVE_SMOKETESTS = 'RECEIVE_SMOKETESTS';
export type RECEIVE_SMOKETESTS = typeof RECEIVE_SMOKETESTS;